bug_tracker/config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'home' => 'static_pages#home'

  get 'about' => 'static_pages#about'

  resources :comments
  resources :bugs

end

bug_tracker/app/models/bug.rb
class Bug < ActiveRecord::Base
    has_many :comments
    validates(:bug_title, presence: true, length: {minimum: 5})
    validates(:bug_description, presence: true, length: {minimum: 50})
end

bug_tracker/app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :bug
    validates(:comment_content, presence: true)
    validates(:bug_id, presence: true)
end

bug_tracker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

bug_tracker/app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :set_bug, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with :name => "admin", :password => "x251rt" 

  # GET /bugs
  # GET /bugs.json
  def index
    @bugs = Bug.all
  end

  # GET /bugs/1
  # GET /bugs/1.json
  def show
  end

  # GET /bugs/new
  def new
    @bug = Bug.new
  end

  # GET /bugs/1/edit
  def edit
  end

  # POST /bugs
  # POST /bugs.json
  def create
    @bug = Bug.new(bug_params)

    respond_to do |format|
      if @bug.save
        format.html { redirect_to @bug, notice: 'Bug was successfully created.' }
        format.json { render :show, status: :created, location: @bug }
      else
        format.html { render :new }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bugs/1
  # PATCH/PUT /bugs/1.json
  def update
    respond_to do |format|
      if @bug.update(bug_params)
        format.html { redirect_to @bug, notice: 'Bug was successfully updated.' }
        format.json { render :show, status: :ok, location: @bug }
      else
        format.html { render :edit }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bugs/1
  # DELETE /bugs/1.json
  def destroy
    @bug.destroy
    respond_to do |format|
      format.html { redirect_to bugs_url, notice: 'Bug was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bug
      @bug = Bug.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bug_params
      params.require(:bug).permit(:bug_title, :bug_description)
    end
end

bug_tracker/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with :name => "admin", :password => "x251rt" 

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:comment_content, :bug_id)
    end
end

bug_tracker/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

bug_tracker/app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title = '')
        base_title = "Bug Tracker Manager"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end
end

bug_tracker/app/helpers/bugs_helper.rb
module BugsHelper
end

bug_tracker/app/helpers/comments_helper.rb
module CommentsHelper
end

bug_tracker/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

bug_tracker/app/views/bugs/_form.html.erb
<%= form_for(@bug) do |f| %>

  <div class="field">
    <%= f.label :bug_title %><br>
    <%= f.text_field :bug_title %>
  </div>
  <div class="field">
    <%= f.label :bug_description %><br>
    <%= f.text_field :bug_description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

bug_tracker/app/views/bugs/edit.html.erb
<% provide(:title, 'Edit ' + @bug.bug_title) %>
<h1>Editing Bug</h1>

<hr/><br/>

<%= render 'shared/bug_error_messages' %>

<%= render 'form' %>

<%= link_to 'Show', @bug %> |
<%= link_to 'Back to manage bugs', bugs_path %>

bug_tracker/app/views/bugs/index.html.erb
<% provide(:title, 'Manage Bugs') %>

<h1>Manage Bugs</h1>

<hr/><br/>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Id</th>
      <th>Bug title</th>
      <th>Bug description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bugs.each do |bug| %>
      <tr>
        <td><%= bug.id %></td>
        <td><%= bug.bug_title %></td>
        <td><%= bug.bug_description %></td>
        <td><%= link_to 'Show', bug %></td>
        <td><%= link_to 'Edit', edit_bug_path(bug) %></td>
        <td><%= link_to 'Destroy', bug, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Bug', new_bug_path,  class: "btn btn-success" %>

bug_tracker/app/views/bugs/new.html.erb
<% provide(:title, 'Add bug') %>

<h1>Add Bug</h1>

<hr/><br/>

<%= render 'shared/bug_error_messages' %>

<%= render 'form' %>

<%= link_to 'Back to manage bugs', bugs_path %>

bug_tracker/app/views/bugs/show.html.erb
<% provide(:title, @bug.bug_title) %>
<div class="jumbotron">
  <h1 class="main_title"><%= @bug.bug_title %></h1>
    <hr/>

    <strong>Bug description:</strong><br/><br/>
      <p class="description">
        <%= @bug.bug_description %>
    </p>

    <hr/>

      <%= link_to 'Edit bug', edit_bug_path(@bug) %> |
      <%= link_to 'Back to manage bugs', bugs_path %>
</div>

bug_tracker/app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
    
  <div class="field">
    <%= f.label :comment_content %><br>
    <%= f.text_field :comment_content %>
  </div>
  <div class="field">
    <%= f.label :bug_id %><br>
    <%= f.number_field :bug_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

bug_tracker/app/views/comments/edit.html.erb
<% provide(:title, 'Edit comment') %>

<h1>Editing Comment</h1>

<hr/><br/>

<%= render 'shared/comments_error_messages' %>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back to manage comments', comments_path %>

bug_tracker/app/views/comments/index.html.erb
<% provide(:title, 'Manage comments') %>

<h1>Manage Comments</h1>

<hr/><br/>

<table class="table table-hover">
  <thead>
    <tr>
        <th>Id</th>
      <th>Comment content</th>
      <th>Bug id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.id %></td>
        <td><%= comment.comment_content %></td>
        <td><%= comment.bug_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Comment', new_comment_path, class: "btn btn-success" %>

bug_tracker/app/views/comments/new.html.erb
<% provide(:title, 'Add comment') %>

<h1>Add Comment</h1>

<hr/><br/>

<%= render 'shared/comments_error_messages' %>

<%= render 'form' %>

<%= link_to 'Back to manage comments', comments_path %>

bug_tracker/app/views/comments/show.html.erb
<% provide(:title, 'Comment details') %>
<div class="jumbotron">
  <h1 class="main_title">Comment on bug_id #<%= @comment.bug_id %></h1>
    <hr/>

    <strong>Comment:</strong><br/><br/>
      <p class="description">
        <%= @comment.comment_content %>
    </p>

    <hr/>

    <%= link_to 'Edit comment', edit_comment_path(@comment) %> |
    <%= link_to 'Back to manage comments', comments_path %>
</div>

bug_tracker/app/views/layouts/_footer.html.erb
<footer class="footer">
    <div class="container">
  <small>
    The <a href="#">Bug tracking management tool</a>
    by <a href="#">Kévin Vacherot</a>
  </small>
  <nav>
    <ul>
        <li><%= link_to "Home", home_path %></li>
        <li><%= link_to "About",  about_path %></li>
    </ul>
  </nav>
  </div>
</footer>

bug_tracker/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Add Bug", new_bug_path %></li>
          <li><%= link_to "Manage bugs",  bugs_path %></li>
          <li><%= link_to "Add comment", new_comment_path %></li>
          <li><%= link_to "Manage comments", comments_path %></li>
      </ul>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "Home", home_path, class: "blue" %></li>
        <li><%= link_to "About",  about_path %></li>
      </ul>
    </nav>
  </div>
</header>

bug_tracker/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

bug_tracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render "layouts/shim" %>
</head>
<body>
    <%= render "layouts/header" %>

    <div class="container">
        <%= yield %>
    </div>

    <%= render "layouts/footer" %>
    <%= debug(params) if Rails.env.development? %>
</body>
</html>

bug_tracker/app/views/shared/_bug_error_messages.html.erb
<% if @bug.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@bug.errors.count, "error") %>.
    </div>
    <ul>
    <% @bug.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

bug_tracker/app/views/shared/_comments_error_messages.html.erb
<% if @comment.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@comment.errors.count, "error") %>.
    </div>
    <ul>
    <% @comment.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

bug_tracker/app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<p>
    Nous sommes des élèves qui expérimentons la technologie Ruby on Rails via la création de cet outil de gestionnaire de bug
</p>

bug_tracker/app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center jumbotron">
  <h1 class="main_title">Welcome to Bug Tracker Manager</h1>

  <h2>
    Useful tool that enable an optimized bug tracking management
  </h2>

  <%= link_to "See all bugs", bugs_path, class: "btn btn-lg btn-primary" %>
</div>

bug_tracker/app/views/static_pages/login.html.erb
<% provide(:title, 'Login') %>
<h1>Sign in</h1>